[package]
name = "mini_p2p_file_transfer_system"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bendy = "0.3.3"
chrono = "0.4.41"
flume = "0.11.1"
slint = "1.12.1"
tokio = "1.46.1"
torrex = "0.2.1"
url = "2.5.4"
